GS.Trade.Web/GS.Trade.Web.Mvc.Cfg_01/Controllers/CfgItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GS.DataBase.Configuration.Dal;
using GS.DataBase.Configuration.Model;
using Microsoft.Ajax.Utilities;

namespace GS.Trade.Web.Mvc.Cfg_01.Controllers
{
    [Authorize(Users = @"gs_trade@mail.ru")]
    public class CfgItemsController : Controller
    {
        private ConfigurationContext db = new ConfigurationContext();

        // GET: CfgItems
        public ActionResult Index(long? cnfId)
        {
            ViewBag.ConfigurationId = cnfId;

            var items = db.GetItems(cnfId);
            
            return View(items.ToList());
        }
        public ActionResult ToEnable(long? cnfId, long? itemId)
        {
            ViewBag.ConfigurationId = cnfId;
            ViewBag.CnfItemId = itemId;

            db.UpdateCnfItemEnables(cnfId, itemId, EnDisEnum.Enabled);
            var items = db.GetItems(cnfId);
            
            return View("Index", items.ToList());
        }
        public ActionResult ToDisable(long? cnfId, long? itemId)
        {
            ViewBag.ConfigurationId = cnfId;
            ViewBag.CnfItemId = itemId;

            db.UpdateCnfItemEnables(cnfId, itemId, EnDisEnum.Disabled);
            var items = db.GetItems(cnfId);

            return View("Index", items.ToList());
        }

        // GET: CfgItems/Details/5
        public ActionResult Details(long? cnfId, long? itemId)
        {
            ViewBag.CnfId = cnfId;

            ViewBag.ConfigurationId = cnfId;
            ViewBag.CnfItemId = itemId;

            if (itemId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(itemId);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // GET: CfgItems/Create
        public ActionResult Create()
        {
            ViewBag.ConfigurationId = new SelectList(db.Configurations, "Id", "Code");
            return View();
        }

        // POST: CfgItems/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ConfigurationId,Enabled,TrCount,Code,Catalog,Obj")] Item item)
        {
            if (ModelState.IsValid)
            {
                //db.Items.Add(item);
                //db.SaveChanges();
                //var conf = item.Configuration;
                var conf = db.Configurations.Find(item.ConfigurationId);
                if (conf == null) 
                    return RedirectToAction("Index");
                var items = db.Items.Where(i => i.ConfigurationId == item.ConfigurationId);
                var it = items.FirstOrDefault(i => i.Code == item.Code);
                if (it != null)
                    return RedirectToAction("Index");
                //conf.Add(item);
                db.Items.Add(item);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ConfigurationId = new SelectList(db.Configurations, "Id", "Code", item.ConfigurationId);
            return View(item);
        }

        // GET: CfgItems/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            ViewBag.ConfigurationId = new SelectList(db.Configurations, "Id", "Code", item.ConfigurationId);
            return View(item);
        }

        // POST: CfgItems/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ConfigurationId,Enabled,TrCount,Code,Catalog,Obj")] Item item)
        {
            if (ModelState.IsValid)
            {
                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ConfigurationId = new SelectList(db.Configurations, "Id", "Code", item.ConfigurationId);
            return View(item);
        }

        // GET: CfgItems/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: CfgItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Item item = db.Items.Find(id);
            db.Items.Remove(item);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GS.Trade.Web/GS.Trade.Web.Mvc.Cfg_01/Controllers/CfgTransController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GS.DataBase.Configuration.Dal;
using GS.DataBase.Configuration.Model;

namespace GS.Trade.Web.Mvc.Cfg_01.Controllers
{
    [Authorize(Users = @"gs_trade@mail.ru")]
    public class CfgTransController : Controller
    {
        private ConfigurationContext db = new ConfigurationContext();

        // GET: CfgTrans
        public ActionResult Index(long? cnfItemId)
        {
            IQueryable<Transaction> ts;
            if (cnfItemId == null)
                ts = db.Transactions
                    .Include(t => t.Item)
                    .OrderByDescending(t=>t.DT);
            else
                ts = db.Transactions
                        .Where(t => t.ItemId == cnfItemId)
                        .Include(t => t.Item)
                        .OrderByDescending(t => t.DT);
            
            return View(ts.ToList());
        }
        public ActionResult Index2(long? cnfId)
        {
            IQueryable<Transaction> ts;
            if (cnfId == null)
                ts = db.Transactions
                    .Include(t => t.Item)
                    .OrderByDescending(t => t.DT);
            else
            
                ts = db.Transactions
                        .Include(t => t.Item)
                        .Where(t => t.Item.ConfigurationId == cnfId)
                        .OrderByDescending(t => t.DT);
            
            return View("Index",ts.ToList());
        }

        // GET: CfgTrans/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            return View(transaction);
        }

        // GET: CfgTrans/Create
        public ActionResult Create()
        {
            ViewBag.ItemId = new SelectList(db.Items, "Id", "Code");
            return View();
        }

        // POST: CfgTrans/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ItemId,Result,Source,Operation,Object,DT")] Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                db.Transactions.Add(transaction);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ItemId = new SelectList(db.Items, "Id", "Code", transaction.ItemId);
            return View(transaction);
        }

        // GET: CfgTrans/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            ViewBag.ItemId = new SelectList(db.Items, "Id", "Code", transaction.ItemId);
            return View(transaction);
        }

        // POST: CfgTrans/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ItemId,Result,Source,Operation,Object,DT")] Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                db.Entry(transaction).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ItemId = new SelectList(db.Items, "Id", "Code", transaction.ItemId);
            return View(transaction);
        }

        // GET: CfgTrans/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            return View(transaction);
        }

        // POST: CfgTrans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Transaction transaction = db.Transactions.Find(id);
            db.Transactions.Remove(transaction);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DeleteAll()
        {
            var ts = db.Transactions.ToList();

            db.Transactions.RemoveRange(ts);
            db.SaveChanges();

            return View("Index", db.Transactions.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GS.Trade.Web/GS.Trade.Web.Mvc.Cfg_01/Controllers/ConfigurationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GS.DataBase.Configuration.Dal;
using GS.DataBase.Configuration.Model;

namespace GS.Trade.Web.Mvc.Cfg_01.Controllers
{
    [Authorize(Users = @"gs_trade@mail.ru")]
    //[Authorize]
    public class ConfigurationsController : Controller
    {
        private readonly ConfigurationContext db = new ConfigurationContext();

        //[Authorize]
        // GET: Configurations
        public ActionResult Index()
        {
            return View(db.Configurations.ToList());
        }

        public ActionResult ToEnable(long? cnfId)
        {
            db.UpdateCnfEnables(cnfId, EnDisEnum.Enabled);

            return View("Index", db.Configurations.ToList());
        }
        public ActionResult ToDisable(long? cnfId)
        {
            db.UpdateCnfEnables(cnfId, EnDisEnum.Disabled);

            return View("Index", db.Configurations.ToList());
        }
        public ActionResult UpdateToken(long? cnfId)
        {
            db.UpdateToken(cnfId);

            return View("Index", db.Configurations.ToList());
        }
        public ActionResult UpdateExpireDate(long? cnfId)
        {
            db.UpdateExpireDate(cnfId);

            return View("Index", db.Configurations.ToList());
        }

        // GET: Configurations/Details/5
        public ActionResult Details(long? id)
        {
            ViewBag.ConfigurationId = id;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Configuration configuration = db.Configurations.Find(id);
            if (configuration == null)
            {
                return HttpNotFound();
            }
            return View(configuration);
        }
       // [Authorize]
        // GET: Configurations/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Configurations/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Id,Enabled,Code,Name,Description,CreatedDT,ModifiedDT")] Configuration configuration)
        public ActionResult Create([Bind(Include = "Id,Enabled,Code,Catalog")] Configuration configuration)
        {
            if (ModelState.IsValid)
            {
                //db.Configurations.Add(configuration);
                //db.SaveChanges();
                db.Add(configuration);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(configuration);
        }
       // [Authorize]
        // GET: Configurations/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Configuration configuration = db.Configurations.Find(id);
            if (configuration == null)
            {
                return HttpNotFound();
            }
            return View(configuration);
        }

        // POST: Configurations/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "Id,Enabled,Code,Name,Description,CreatedDT,ModifiedDT")] Configuration configuration)
        public ActionResult Edit([Bind(Include = "Id,Enabled,Code,Catalog,Token,IncDaysExpire")] Configuration configuration)
        {
            if (ModelState.IsValid)
            {
                db.Entry(configuration).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(configuration);
        }
       // [Authorize]
        // GET: Configurations/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Configuration configuration = db.Configurations.Find(id);
            if (configuration == null)
            {
                return HttpNotFound();
            }
            return View(configuration);
        }

        // POST: Configurations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Configuration configuration = db.Configurations.Find(id);
            db.Configurations.Remove(configuration);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GS.Trade.Web/GS.Trade.Web.Mvc.Cfg_01/Views/CfgItems/Create.cshtml
@model GS.DataBase.Configuration.Model.Item

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Item</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ConfigurationId, "ConfigurationId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ConfigurationId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ConfigurationId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Enabled, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Enabled, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Enabled, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TrCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TrCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TrCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Catalog, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Catalog, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Catalog, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Obj, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Obj, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Obj, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.CreatedDT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedDT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedDT, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GS.Trade.Web/GS.Trade.Web.Mvc.Cfg_01/Views/CfgItems/Delete.cshtml
@model GS.DataBase.Configuration.Model.Item

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Item</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Configuration.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Configuration.Code)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Catalog)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Catalog)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Obj)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Obj)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Enabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Enabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrCount)
        </dd>

       

       

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDT)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GS.Trade.Web/GS.Trade.Web.Mvc.Cfg_01/Views/CfgItems/Details.cshtml
@model GS.DataBase.Configuration.Model.Item

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Item</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            ConfigurationID
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Configuration.Id)
        </dd>
        <dt>
            ConfigurationCode
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Configuration.Code)
        </dd>
        <dt>
            ID
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Enabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Enabled)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Catalog)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Catalog)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CatalogExt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CatalogExt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Obj)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Obj)
        </dd>
       
        <dt>
            @Html.DisplayNameFor(model => model.CreatedDT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDT)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index", "CfgItems", new {cnfId = @ViewBag.CnfId}, null)
</p>

GS.Trade.Web/GS.Trade.Web.Mvc.Cfg_01/Views/CfgItems/Index.cshtml
@model IEnumerable<GS.DataBase.Configuration.Model.Item>

@{
    ViewBag.Title = "Index";
}

<h4>Configuration Items</h4>

<p>
    <b>
        @Html.ActionLink("Create New", "Create")
        @*@Html.ActionLink("Enable All", "ToEnable")
        @Html.ActionLink("Disable All", "ToDisable")*@
        @Html.ActionLink("Enable", "ToEnable", "CfgItems", new { cnfId = @ViewBag.ConfigurationId }, null)
        @Html.ActionLink("Disable", "ToDisable", "CfgItems", new { cnfId = @ViewBag.ConfigurationId }, null)
    </b>
</p>
<table class="table">
    <tr>
        <th>ID</th>
        <th>
            Configuration
            @*@Html.DisplayNameFor(model => model.Configuration.Code)*@
        </th>
        <th>ID</th>
       
        <th>
            @Html.DisplayNameFor(model => model.Code)
        </th>
       
        <th>
            @Html.DisplayNameFor(model => model.Catalog)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CatalogExt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Obj)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Enabled)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.TrCount)
        </th>*@
        @*<th>
            @Html.DisplayNameFor(model => model.CreatedDT)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.ModifiedDT)
        </th>
        <th></th>
        <th></th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Configuration.Id)
        </td>
        <td>
            @{
                string cnfCode = item.Configuration.Code;
            }
            @Html.ActionLink(cnfCode, "Details", "Configurations", new { id = item.ConfigurationId }, null)
            @Html.ActionLink("Items", "Index", "CfgItems", new { cnfId = item.ConfigurationId }, null)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        
        <td>
            @{
                string cnfItemCode = item.Code;
            }
            @Html.ActionLink(cnfItemCode, "Details", "CfgItems", new { cnfId = item.ConfigurationId, itemId = item.Id }, null)
        </td>    
        <td>
            @Html.DisplayFor(modelItem => item.Catalog)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CatalogExt)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Obj)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Enabled)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.TrCount)
        </td>*@
        @*<td>
            @Html.DisplayFor(modelItem => item.CreatedDT)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.ModifiedDT)
        </td>
        <td>
            @Html.ActionLink("Trans", "Index", "CfgTrans", new { cnfItemId = item.Id }, null)
        </td>
        <td>
            @Html.ActionLink("Enable", "ToEnable", "CfgItems", new { cnfId = item.ConfigurationId , itemId = item.Id }, null)
            @Html.ActionLink("Disable", "ToDisable", "CfgItems", new { cnfId = item.ConfigurationId, itemId = item.Id }, null)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id })
            @Html.ActionLink("Details", "Details", new { cnfId = item.ConfigurationId, itemId=item.Id })
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>